"""empty message

Revision ID: 568b219100b
Revises: None
Create Date: 2016-08-01 17:51:39.379937

"""

# revision identifiers, used by Alembic.
revision = '568b219100b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('browser', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('exp_name', sa.String(), nullable=False),
    sa.Column('begin_session', sa.DateTime(), nullable=False),
    sa.Column('begin_experiment', sa.DateTime(), nullable=True),
    sa.Column('results', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('category_switch',
    sa.Column('cs_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('trial_num', sa.Integer(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('reaction_time', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('block', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('user_answer', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('cs_id')
    )
    op.create_table('event_data',
    sa.Column('ev_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('exp_name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('interval', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('ev_id')
    )
    op.create_table('keep_track',
    sa.Column('kt_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('trial_num', sa.Integer(), nullable=True),
    sa.Column('reaction_time', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.String(), nullable=True),
    sa.Column('block', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('target_words', sa.String(), nullable=True),
    sa.Column('input_words', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('kt_id')
    )
    op.create_table('question_data',
    sa.Column('q_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('exp_name', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('distraction', sa.String(), nullable=True),
    sa.Column('openended', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('q_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_data')
    op.drop_table('keep_track')
    op.drop_table('event_data')
    op.drop_table('category_switch')
    op.drop_table('session')
    ### end Alembic commands ###
