### Script to recover the order of trials in category_switch
### Uses original stim order (from coffee script) and generates ordered csv
### With correct answer. Calculates if trials are repeat or switch based on
### correct answers.

import pandas as pd

# name in all_stim, name in output file
blocks_order = [('living_prac', 'livingPrac'),
 ('living_real', 'livingReal'),
 ('size_prac', 'sizePrac'),
 ('size_real', 'sizeReal'),
 ('mixed_prac', 'mixedPrac'),
 ('mixed_real_1', 'mixedReal1'),
 ('mixed_real_2', 'mixedReal2')]

all_stim = {'living_prac': [['alligator', 'living'],
  ['snowflake', 'nonliv'],
  ['bicycle', 'nonliv'],
  ['mushroom', 'living'],
  ['cloud', 'nonliv'],
  ['goldfish', 'living'],
  ['lizard', 'living'],
  ['table', 'nonliv'],
  ['marble', 'nonliv'],
  ['shark', 'living'],
  ['knob', 'nonliv'],
  ['lion', 'living']],
 'living_real': [['marble', 'nonliv'],
  ['oak', 'living'],
  ['lizard', 'living'],
  ['coat', 'nonliv'],
  ['sparrow', 'living'],
  ['goldfish', 'living'],
  ['lion', 'living'],
  ['alligator', 'living'],
  ['pebble', 'nonliv'],
  ['shark', 'living'],
  ['knob', 'nonliv'],
  ['table', 'nonliv'],
  ['shark', 'living'],
  ['bicycle', 'nonliv'],
  ['cloud', 'nonliv'],
  ['marble', 'nonliv'],
  ['cloud', 'nonliv'],
  ['alligator', 'living'],
  ['sparrow', 'living'],
  ['lizard', 'living'],
  ['snowflake', 'nonliv'],
  ['mushroom', 'living'],
  ['lion', 'living'],
  ['pebble', 'nonliv'],
  ['bicycle', 'nonliv'],
  ['table', 'nonliv'],
  ['oak', 'living'],
  ['mushroom', 'living'],
  ['knob', 'nonliv'],
  ['marble', 'nonliv'],
  ['coat', 'nonliv'],
  ['goldfish', 'living'],
  ['snowflake', 'nonliv'],
  ['oak', 'living']],
 'mixed_prac': [['marble', 'nonliv'],
  ['table', 'nonliv'],
  ['alligator', 'big'],
  ['sparrow', 'small'],
  ['snowflake', 'small'],
  ['goldfish', 'small'],
  ['mushroom', 'living'],
  ['cloud', 'nonliv'],
  ['knob', 'small'],
  ['oak', 'living'],
  ['marble', 'small'],
  ['bicycle', 'nonliv'],
  ['lizard', 'living'],
  ['knob', 'nonliv'],
  ['lizard', 'small'],
  ['bicycle', 'big'],
  ['pebble', 'nonliv'],
  ['shark', 'big'],
  ['sparrow', 'living'],
  ['lion', 'living'],
  ['goldfish', 'living'],
  ['lion', 'big'],
  ['table', 'big'],
  ['coat', 'big']],
 'mixed_real_1': [['table', 'big'],
  ['pebble', 'small'],
  ['shark', 'living'],
  ['coat', 'nonliv'],
  ['alligator', 'living'],
  ['pebble', 'small'],
  ['lion', 'living'],
  ['snowflake', 'nonliv'],
  ['lizard', 'living'],
  ['marble', 'small'],
  ['bicycle', 'big'],
  ['shark', 'big'],
  ['alligator', 'living'],
  ['lizard', 'small'],
  ['lion', 'big'],
  ['goldfish', 'small'],
  ['alligator', 'big'],
  ['pebble', 'nonliv'],
  ['shark', 'big'],
  ['snowflake', 'nonliv'],
  ['mushroom', 'living'],
  ['snowflake', 'small'],
  ['knob', 'small'],
  ['goldfish', 'living'],
  ['cloud', 'big'],
  ['mushroom', 'small'],
  ['bicycle', 'nonliv'],
  ['shark', 'living'],
  ['knob', 'small'],
  ['marble', 'small'],
  ['oak', 'big'],
  ['snowflake', 'small'],
  ['coat', 'big'],
  ['knob', 'nonliv'],
  ['sparrow', 'living'],
  ['lion', 'living'],
  ['coat', 'big'],
  ['mushroom', 'living'],
  ['table', 'nonliv'],
  ['oak', 'living'],
  ['marble', 'nonliv'],
  ['knob', 'nonliv'],
  ['oak', 'big'],
  ['lizard', 'living'],
  ['mushroom', 'small'],
  ['oak', 'living'],
  ['goldfish', 'living'],
  ['bicycle', 'nonliv'],
  ['sparrow', 'small'],
  ['cloud', 'nonliv'],
  ['pebble', 'nonliv'],
  ['goldfish', 'small'],
  ['table', 'big'],
  ['coat', 'nonliv'],
  ['bicycle', 'big'],
  ['cloud', 'big']],
 'mixed_real_2': [['shark', 'living'],
  ['table', 'nonliv'],
  ['goldfish', 'small'],
  ['coat', 'big'],
  ['lizard', 'small'],
  ['knob', 'nonliv'],
  ['coat', 'nonliv'],
  ['snowflake', 'small'],
  ['marble', 'nonliv'],
  ['mushroom', 'small'],
  ['table', 'big'],
  ['cloud', 'big'],
  ['alligator', 'big'],
  ['lizard', 'living'],
  ['cloud', 'nonliv'],
  ['sparrow', 'small'],
  ['mushroom', 'living'],
  ['alligator', 'living'],
  ['table', 'big'],
  ['goldfish', 'living'],
  ['cloud', 'big'],
  ['lion', 'big'],
  ['snowflake', 'nonliv'],
  ['shark', 'living'],
  ['sparrow', 'living'],
  ['marble', 'small'],
  ['pebble', 'nonliv'],
  ['knob', 'nonliv'],
  ['alligator', 'big'],
  ['shark', 'big'],
  ['pebble', 'small'],
  ['snowflake', 'small'],
  ['bicycle', 'big'],
  ['lion', 'living'],
  ['oak', 'living'],
  ['goldfish', 'living'],
  ['shark', 'big'],
  ['sparrow', 'small'],
  ['oak', 'living'],
  ['mushroom', 'living'],
  ['lizard', 'living'],
  ['bicycle', 'big'],
  ['marble', 'small'],
  ['alligator', 'living'],
  ['snowflake', 'nonliv'],
  ['lion', 'living'],
  ['pebble', 'small'],
  ['oak', 'big'],
  ['coat', 'nonliv'],
  ['bicycle', 'nonliv'],
  ['knob', 'small'],
  ['sparrow', 'living'],
  ['lion', 'big'],
  ['mushroom', 'small'],
  ['knob', 'small'],
  ['bicycle', 'nonliv']],
 'size_prac': [['pebble', 'small'],
  ['bicycle', 'big'],
  ['sparrow', 'small'],
  ['coat', 'big'],
  ['lion', 'big'],
  ['lizard', 'small'],
  ['snowflake', 'small'],
  ['shark', 'big'],
  ['goldfish', 'small'],
  ['knob', 'small'],
  ['cloud', 'big'],
  ['table', 'big']],
 'size_real': [['table', 'big'],
  ['knob', 'small'],
  ['pebble', 'small'],
  ['oak', 'big'],
  ['bicycle', 'big'],
  ['coat', 'big'],
  ['shark', 'big'],
  ['lizard', 'small'],
  ['alligator', 'big'],
  ['lion', 'big'],
  ['snowflake', 'small'],
  ['bicycle', 'big'],
  ['shark', 'big'],
  ['lizard', 'small'],
  ['table', 'big'],
  ['mushroom', 'small'],
  ['marble', 'small'],
  ['cloud', 'big'],
  ['oak', 'big'],
  ['knob', 'small'],
  ['pebble', 'small'],
  ['sparrow', 'small'],
  ['goldfish', 'small'],
  ['cloud', 'big'],
  ['mushroom', 'small'],
  ['snowflake', 'small'],
  ['goldfish', 'small'],
  ['knob', 'small'],
  ['table', 'big'],
  ['alligator', 'big'],
  ['sparrow', 'small'],
  ['marble', 'small'],
  ['lion', 'big'],
  ['coat', 'big']]}

trial_type = {'small' : 'size',
              'big' : 'size',
              'living' : 'living',
              'nonliv' : 'living'}

output = []
for og, on in blocks_order:
    pt = None
    for t in all_stim[og]:
        rep = 0
        if pt:
            if trial_type[t[1]] == trial_type[pt]:
                rep = 1
        output.append([on] + t + [rep])
        pt = t[1]

df = pd.DataFrame(output, columns=['block', 'stimulus', 'corr_answer', 'repeat'])
df.to_csv('trial_type_order.csv')
